version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP-интерфейс
      - "9000:9000"  # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: 'default'
      CLICKHOUSE_USER: 'user'
      CLICKHOUSE_PASSWORD: 'password'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  clickhouse_data: